# 制作skywalking-agent镜像
FROM busybox:latest
LABEL maintainer="fengsulin"
COPY apache-skywalking-apm-bin/agent/ /usr/skywalking/agent/
#打镜像tag registry.cn-hangzhou.aliyuncs.com/fsl-devops/skywalking-agent-sidecar:8.5.0

